
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-deployment
  labels:
    app: centos/httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos/httpd
  template:
    metadata:
      labels:
        app: centos/httpd 
    spec:
      containers:
      - name: centcontainer
        image: centos/httpd
        ports:
        - containerPort: 80
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: centos/httpd 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31110
